export var testJokes = [
    {   
        id: "1",
        userId: "1", 
        jokeCategoryId: "1", 
        joke: "This is my joke title", 
        hiddenPunchline: "This is the punchline", 
        showPunch: false,
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 1, 
        downvotes: 1, 
        source: null, 
        sourceURL: "jokeSourceURL.com", 
        flags: null, 
        rating: null
    },
    {   
        id: "2",
        userId: "2", 
        jokeCategoryId: "2", 
        joke: "What’s the difference between a literalist and a kleptomaniac?", 
        hiddenPunchline: "A literalist takes things literally. A kleptomaniac takes things, literally.", 
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 2, 
        downvotes: 2, 
        source: "Reddit", 
        sourceURL: "https://www.reddit.com/r/Jokes/comments/dsf3y2/whats_the_difference_between_a_literalist_and_a/", 
        flags: null, 
        rating: null
    },
    {   
        id: "3",
        userId: "3", 
        jokeCategoryId: "3", 
        joke: "A penguin is driving to the mall when all of a sudden his engine starts running really rough, and smoke is coming from under the hood. Luckily, there's an auto repair shop right next to the mall, so he pulls in there. The mechanic says he'll be glad to take a look, but he won't be able to get to it for a couple hours. The penguin says fine, and walks across the street to the mall. \n He kills time walking around the mall, does some window shopping, buys an ice cream cone, etc. Finally the two hours are up and he goes back to the mechanic. \n The penguin says, \"Have you had time to look at my engine?\" \n The mechanic says, \"Yeah, it looks like you blew a seal.\"", 
        hiddenPunchline: "The penguin says, \"No, that's just ice cream.\"", 
        showPunch: false,
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 3, 
        downvotes: 3, 
        source: "Reddit", 
        sourceURL: "https://www.reddit.com/r/Jokes/comments/ccaid8/my_girlfriend_told_me_this_joke_ten_years_ago/", 
        flags: null, 
        rating: null
    },
    {   
        id: "4",
        userId: "4", 
        jokeCategoryId: "1", 
        joke: "This is my joke title 4", 
        hiddenPunchline: "This is the punchline 4", 
        showPunch: false,
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 1, 
        downvotes: 1, 
        source: "Source", 
        sourceURL: "jokeSourceURL.com", 
        flags: null, 
        rating: null
    },
    {   
        id: "5",
        userId: "5", 
        jokeCategoryId: "1", 
        joke: "This is my joke title 5", 
        hiddenPunchline: "This is the punchline 5", 
        showPunch: false,
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 1, 
        downvotes: 1, 
        source: "Source", 
        sourceURL: "jokeSourceURL.com", 
        flags: null, 
        rating: null
    },
    {   
        id: "6",
        userId: "6", 
        jokeCategoryId: "1", 
        joke: "This is my joke title 4", 
        hiddenPunchline: "This is the punchline 4", 
        showPunch: false,
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 1, 
        downvotes: 1, 
        source: "Source", 
        sourceURL: "jokeSourceURL.com", 
        flags: null, 
        rating: null
    }
];