export var testJokes = [
    {   
        id: "1",
        userId: "1", 
        jokeCategoryId: "1", 
        joke: "This is my joke title", 
        hiddenPunchline: "This is the punchline", 
        showPunch: false,
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 1, 
        downvotes: 1, 
        source: "Source", 
        sourceURL: "jokeSourceURL.com", 
        flags: null, 
        rating: null
    },
    {   
        id: "2",
        userId: "2", 
        jokeCategoryId: "2", 
        joke: "This is my joke title 2", 
        hiddenPunchline: "This is the punchline 2", 
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 2, 
        downvotes: 2, 
        source: "Source", 
        sourceURL: "jokeSourceURL.com", 
        flags: null, 
        rating: null
    },
    {   
        id: "3",
        userId: "3", 
        jokeCategoryId: "3", 
        joke: "This is my joke title 3", 
        hiddenPunchline: "This is the punchline 3", 
        showPunch: false,
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 3, 
        downvotes: 3, 
        source: "Source", 
        sourceURL: "jokeSourceURL.com", 
        flags: null, 
        rating: null
    },
    {   
        id: "4",
        userId: "4", 
        jokeCategoryId: "1", 
        joke: "This is my joke title 4", 
        hiddenPunchline: "This is the punchline 4", 
        showPunch: false,
        uploaded: "2018-8-3 11:12:40", 
        upvotes: 1, 
        downvotes: 1, 
        source: "Source", 
        sourceURL: "jokeSourceURL.com", 
        flags: null, 
        rating: null
    }
];